name: Setup Self-Hosted Runner

on: [push]

jobs:
  setup-runner:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: SSH into Azure VM and setup runner
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          mkdir actions-runner1 && cd actions-runner1
          curl -o actions-runner-linux-x64-2.281.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.281.1/actions-runner-linux-x64-2.281.1.tar.gz
          tar xzf ./actions-runner-linux-x64-2.281.1.tar.gz
          ./config.sh --url ${{ secrets.REPOSITORY_URL }} --token ${{ secrets.RUNNER_TOKEN }}
          sudo ./svc.sh install
          sudo ./svc.sh start

    - name: Wait for runner to register
      run: sleep 60
