name: Set up Self-Hosted Runner

on:
  push:
    branches:
      - main
jobs:
  setup-runner:
    runs-on: self-hosted 
    name: Set up and Configure Self-Hosted Runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: configure self-hosted runner
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Install GitHub runner on the VM
            # Create a folder
          mkdir actions-runner1 && cd actions-runner1# Download the latest runner package
          curl -o actions-runner-linux-x64-2.316.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.316.1/actions-runner-linux-x64-2.316.1.tar.gz# Optional: Validate the hash
          echo "d62de2400eeeacd195db91e2ff011bfb646cd5d85545e81d8f78c436183e09a8  actions-runner-linux-x64-2.316.1.tar.gz" | shasum -a 256 -c# Extract the installer
          tar xzf ./actions-runner-linux-x64-2.316.1.tar.gz
          ./config.sh --url https://github.com/sandhiyatech/My-learnings --token AS33PNG6KMOQBOOBO3VNTFLGL5IHC
          sudo ./svc.sh install
          sudo ./svc.sh start
          
