name: Set up Self-Hosted Runner

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  setup-runner:
    runs-on: ubuntu-latest
    name: Set up and Configure Self-Hosted Runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        auth-type: IDENTITY
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: configure self-hosted runner
      id: azure-vm
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          # Variables
          RESOURCE_GROUP="BH-Team"
          VM_NAME="vm-san-infra"
          ADMIN_USERNAME="azureuser"
          # Get the VM's public IP address
          IP_ADDRESS=$(az vm list-ip-addresses --resource-group $RESOURCE_GROUP --name $VM_NAME --query [0].virtualMachine.network.publicIpAddresses[0].ipAddress -o tsv)
          echo "VM IP Address: $IP_ADDRESS"

          # Install GitHub runner on the VM
          ssh -o StrictHostKeyChecking=no $ADMIN_USERNAME@$IP_ADDRESS << EOF
            sudo apt-get update
            sudo apt-get install -y curl
            curl -o actions-runner-linux-x64-${{ env.RUNNER_VERSION }}.tar.gz -L https://github.com/actions/runner/releases/download/v${{ env.RUNNER_VERSION }}/actions-runner-linux-x64-${{ env.RUNNER_VERSION }}.tar.gz
            tar xzf ./actions-runner-linux-x64-${{ env.RUNNER_VERSION }}.tar.gz
            ./config.sh --url ${{ secrets.REPOSITORY_URL }} --token ./config.cmd --url https://github.com/sandhiyatech/My-learnings --token AS33PNBLKH7VJVBQYIRFQZLGL4D3Q
            sudo ./svc.sh install
            sudo ./svc.sh start
          EOF
