name: Setup Self-Hosted Runner

on: [push]

jobs:
  setup-runner:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

   # - name: Install Azure CLI
   #   run: |
   #   curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

   # - name: Login to Azure
   #   run: |
   #     az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

   # - name: Start Azure VM
   #   run: |
   #     az vm start --resource-group <Resource-Group-Name> --name <VM-Name>

    - name: SSH into Azure VM and setup runner
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          mkdir actions-runner && cd actions-runner
          curl -o actions-runner-linux-x64-2.281.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.281.1/actions-runner-linux-x64-2.281.1.tar.gz
          tar xzf ./actions-runner-linux-x64-2.281.1.tar.gz
          ./config.sh --url ${{ secrets.REPOSITORY_URL }} --token ${{ secrets.RUNNER_TOKEN }}
          sudo ./svc.sh install
          sudo ./svc.sh start

    - name: Wait for runner to register
      run: sleep 60
