name: Setup Additional Self-Hosted Runner

on:
  workflow_dispatch:
    inputs:
      repo_choice:
        description: 'Repository to configure the runner for'
        required: true
        options: 
          - 'https://github.com/sandhiyatech/aws'
          - 'https://github.com/sandhiyatech/retail_store_project'
          - 'https://github.com/sandhiyatech/aws-devops'
      runner_token:
        description: 'Runner token for authentication'
        required: true
      label:
        description: 'Label for the runner'
        required: true
      runner:
        description: 'Name of runner group'
        required: true
      dir_name:
        description: 'Directory name'
        required: true
jobs:
  setup-additional-runner:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: SSH into Azure VM and setup additional runner
      env:
        AZURE_VM_PASSWORD: ${{ secrets.AZURE_VM_PASSWORD }}
      run: |
        sshpass -p "$AZURE_VM_PASSWORD" ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} << EOF
          mkdir -p ${{ github.event.inputs.dir_name}} && cd ${{ github.event.inputs.dir_name}}
          curl -o actions-runner-linux-x64-2.284.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.284.0/actions-runner-linux-x64-2.284.0.tar.gz
          tar xzf ./actions-runner-linux-x64-2.284.0.tar.gz
          ./config.sh --url ${{ github.event.inputs.repo_choice }} --token ${{ github.event.inputs.runner_token }}
          ${{ github.event.inputs.runner }}
          ${{ github.event.inputs.label }}
        EOF
    - name: To make runner online
      run: |
          ./svc.sh install
          ./svc.sh start

    - name: Wait for runner to register
      run: sleep 60
